// Code generated by go-swagger; DO NOT EDIT.

package tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/foxdalas/flagr/swagger_gen/models"
)

// CreateTagGlobalOKCode is the HTTP code returned for type CreateTagGlobalOK
const CreateTagGlobalOKCode int = 200

/*
CreateTagGlobalOK tag just created

swagger:response createTagGlobalOK
*/
type CreateTagGlobalOK struct {

	/*
	  In: Body
	*/
	Payload *models.Tag `json:"body,omitempty"`
}

// NewCreateTagGlobalOK creates CreateTagGlobalOK with default headers values
func NewCreateTagGlobalOK() *CreateTagGlobalOK {

	return &CreateTagGlobalOK{}
}

// WithPayload adds the payload to the create tag global o k response
func (o *CreateTagGlobalOK) WithPayload(payload *models.Tag) *CreateTagGlobalOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create tag global o k response
func (o *CreateTagGlobalOK) SetPayload(payload *models.Tag) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateTagGlobalOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
CreateTagGlobalDefault generic error response

swagger:response createTagGlobalDefault
*/
type CreateTagGlobalDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateTagGlobalDefault creates CreateTagGlobalDefault with default headers values
func NewCreateTagGlobalDefault(code int) *CreateTagGlobalDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateTagGlobalDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create tag global default response
func (o *CreateTagGlobalDefault) WithStatusCode(code int) *CreateTagGlobalDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create tag global default response
func (o *CreateTagGlobalDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create tag global default response
func (o *CreateTagGlobalDefault) WithPayload(payload *models.Error) *CreateTagGlobalDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create tag global default response
func (o *CreateTagGlobalDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateTagGlobalDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
