// Code generated by go-swagger; DO NOT EDIT.

package tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateTagGlobalHandlerFunc turns a function with the right signature into a create tag global handler
type CreateTagGlobalHandlerFunc func(CreateTagGlobalParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateTagGlobalHandlerFunc) Handle(params CreateTagGlobalParams) middleware.Responder {
	return fn(params)
}

// CreateTagGlobalHandler interface for that can handle valid create tag global params
type CreateTagGlobalHandler interface {
	Handle(CreateTagGlobalParams) middleware.Responder
}

// NewCreateTagGlobal creates a new http.Handler for the create tag global operation
func NewCreateTagGlobal(ctx *middleware.Context, handler CreateTagGlobalHandler) *CreateTagGlobal {
	return &CreateTagGlobal{Context: ctx, Handler: handler}
}

/*
	CreateTagGlobal swagger:route POST /tags tag createTagGlobal

CreateTagGlobal create tag global API
*/
type CreateTagGlobal struct {
	Context *middleware.Context
	Handler CreateTagGlobalHandler
}

func (o *CreateTagGlobal) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateTagGlobalParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
