// Code generated by go-swagger; DO NOT EDIT.

package tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteTagGlobalHandlerFunc turns a function with the right signature into a delete tag global handler
type DeleteTagGlobalHandlerFunc func(DeleteTagGlobalParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteTagGlobalHandlerFunc) Handle(params DeleteTagGlobalParams) middleware.Responder {
	return fn(params)
}

// DeleteTagGlobalHandler interface for that can handle valid delete tag global params
type DeleteTagGlobalHandler interface {
	Handle(DeleteTagGlobalParams) middleware.Responder
}

// NewDeleteTagGlobal creates a new http.Handler for the delete tag global operation
func NewDeleteTagGlobal(ctx *middleware.Context, handler DeleteTagGlobalHandler) *DeleteTagGlobal {
	return &DeleteTagGlobal{Context: ctx, Handler: handler}
}

/*
	DeleteTagGlobal swagger:route DELETE /tags/{tagID} tag deleteTagGlobal

DeleteTagGlobal delete tag global API
*/
type DeleteTagGlobal struct {
	Context *middleware.Context
	Handler DeleteTagGlobalHandler
}

func (o *DeleteTagGlobal) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteTagGlobalParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
