// Code generated by go-swagger; DO NOT EDIT.

package tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/foxdalas/flagr/swagger_gen/models"
)

// DeleteTagGlobalOKCode is the HTTP code returned for type DeleteTagGlobalOK
const DeleteTagGlobalOKCode int = 200

/*
DeleteTagGlobalOK deleted

swagger:response deleteTagGlobalOK
*/
type DeleteTagGlobalOK struct {
}

// NewDeleteTagGlobalOK creates DeleteTagGlobalOK with default headers values
func NewDeleteTagGlobalOK() *DeleteTagGlobalOK {

	return &DeleteTagGlobalOK{}
}

// WriteResponse to the client
func (o *DeleteTagGlobalOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*
DeleteTagGlobalDefault generic error response

swagger:response deleteTagGlobalDefault
*/
type DeleteTagGlobalDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteTagGlobalDefault creates DeleteTagGlobalDefault with default headers values
func NewDeleteTagGlobalDefault(code int) *DeleteTagGlobalDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteTagGlobalDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete tag global default response
func (o *DeleteTagGlobalDefault) WithStatusCode(code int) *DeleteTagGlobalDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete tag global default response
func (o *DeleteTagGlobalDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete tag global default response
func (o *DeleteTagGlobalDefault) WithPayload(payload *models.Error) *DeleteTagGlobalDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete tag global default response
func (o *DeleteTagGlobalDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteTagGlobalDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
