// Code generated by go-swagger; DO NOT EDIT.

package tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/foxdalas/flagr/swagger_gen/models"
)

// PutTagOKCode is the HTTP code returned for type PutTagOK
const PutTagOKCode int = 200

/*
PutTagOK tag just updated

swagger:response putTagOK
*/
type PutTagOK struct {

	/*
	  In: Body
	*/
	Payload *models.Tag `json:"body,omitempty"`
}

// NewPutTagOK creates PutTagOK with default headers values
func NewPutTagOK() *PutTagOK {

	return &PutTagOK{}
}

// WithPayload adds the payload to the put tag o k response
func (o *PutTagOK) WithPayload(payload *models.Tag) *PutTagOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put tag o k response
func (o *PutTagOK) SetPayload(payload *models.Tag) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutTagOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
PutTagDefault generic error response

swagger:response putTagDefault
*/
type PutTagDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutTagDefault creates PutTagDefault with default headers values
func NewPutTagDefault(code int) *PutTagDefault {
	if code <= 0 {
		code = 500
	}

	return &PutTagDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the put tag default response
func (o *PutTagDefault) WithStatusCode(code int) *PutTagDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the put tag default response
func (o *PutTagDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the put tag default response
func (o *PutTagDefault) WithPayload(payload *models.Error) *PutTagDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put tag default response
func (o *PutTagDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutTagDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
