// Code generated by go-swagger; DO NOT EDIT.

package tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutTagHandlerFunc turns a function with the right signature into a put tag handler
type PutTagHandlerFunc func(PutTagParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutTagHandlerFunc) Handle(params PutTagParams) middleware.Responder {
	return fn(params)
}

// PutTagHandler interface for that can handle valid put tag params
type PutTagHandler interface {
	Handle(PutTagParams) middleware.Responder
}

// NewPutTag creates a new http.Handler for the put tag operation
func NewPutTag(ctx *middleware.Context, handler PutTagHandler) *PutTag {
	return &PutTag{Context: ctx, Handler: handler}
}

/*
	PutTag swagger:route PUT /tags/{tagID} tag putTag

PutTag put tag API
*/
type PutTag struct {
	Context *middleware.Context
	Handler PutTagHandler
}

func (o *PutTag) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutTagParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
