// Code generated by go-swagger; DO NOT EDIT.

package restapi

import (
	"crypto/tls"
	"encoding/json"
	"io"
	"net/http"

	"github.com/foxdalas/flagr/pkg/config"
	"github.com/foxdalas/flagr/pkg/handler"
	"github.com/foxdalas/flagr/pkg/version"
	"github.com/foxdalas/flagr/swagger_gen/restapi/operations"
	"github.com/sirupsen/logrus"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
)

// This file is safe to edit. Once it exists it will not be overwritten

//go:generate swagger generate server --target ../../swagger_gen --name Flagr --spec ../../docs/api_docs/bundle.yaml

func configureFlags(api *operations.FlagrAPI) {
	// api.CommandLineOptionsGroups = []swag.CommandLineOptionsGroup{ ... }
}

func patchSwaggerVersion(api *operations.FlagrAPI) {
	ver := version.Version
	if ver == "" || ver == "dev" {
		return
	}
	SwaggerJSON = patchVersionInSpec(SwaggerJSON, ver)
	FlatSwaggerJSON = patchVersionInSpec(FlatSwaggerJSON, ver)

	spec, err := loads.Embedded(SwaggerJSON, FlatSwaggerJSON)
	if err == nil {
		api.SetSpec(spec)
	}
}

func patchVersionInSpec(raw json.RawMessage, ver string) json.RawMessage {
	var doc map[string]interface{}
	if err := json.Unmarshal(raw, &doc); err != nil {
		return raw
	}
	if info, ok := doc["info"].(map[string]interface{}); ok {
		info["version"] = ver
	}
	patched, err := json.Marshal(doc)
	if err != nil {
		return raw
	}
	return patched
}

func configureAPI(api *operations.FlagrAPI) http.Handler {
	patchSwaggerVersion(api)
	api.ServeError = errors.ServeError

	api.JSONConsumer = runtime.ConsumerFunc(func(reader io.Reader, data interface{}) error {
		dec := json.NewDecoder(reader)
		dec.UseNumber()
		return dec.Decode(data)
	})

	api.JSONProducer = runtime.ProducerFunc(func(writer io.Writer, data interface{}) error {
		enc := json.NewEncoder(writer)
		enc.SetEscapeHTML(false)
		return enc.Encode(data)
	})
	api.BinProducer = runtime.ByteStreamProducer()

	api.Logger = logrus.Infof
	api.ServerShutdown = config.ServerShutdown

	handler.Setup(api)
	return setupGlobalMiddleware(api.Serve(setupMiddlewares))
}

// The TLS configuration before HTTPS server starts.
func configureTLS(tlsConfig *tls.Config) {
	// Make all necessary changes to the TLS configuration here.
}

// As soon as server is initialized but not run yet, this function will be called.
// If you need to modify a config, store server instance to stop it individually later, this is the place.
// This function can be called multiple times, depending on the number of serving schemes.
// scheme value will be set accordingly: "http", "https" or "unix"
func configureServer(s *http.Server, scheme, addr string) {
}

// The middleware configuration is for the handler executors. These do not apply to the swagger.json document.
// The middleware executes after routing but before authentication, binding and validation
func setupMiddlewares(handler http.Handler) http.Handler {
	return handler
}

// The middleware configuration happens before anything, this middleware also applies to serving the swagger.json document.
// So this is a good place to plug in a panic handling middleware, logging and metrics
func setupGlobalMiddleware(handler http.Handler) http.Handler {
	return config.SetupGlobalMiddleware(handler)
}
